FROM php:8.2-apache

WORKDIR /var/www/html
COPY . /var/www/html

RUN apt-get update && \
    apt-get install -y git unzip curl && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    composer install --no-dev && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 80
CMD ["apache2-foreground"]
